export * from "./AboutUs";
export * from "./Hero";
export * from "./Kinds/hooks/useDataKind";
export * from "./Kinds";
export * from "./MainText";
export * from "./Reviews";
export * from "./TrustUs/hooks/useDataTrustUs";
export * from "./TrustUs";
export * from "./WriteUs";
